# Generated by Django 2.2.3 on 2020-02-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': '施工日志'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': '单位工程'},
        ),
    ]
