# Generated by Django 2.2.3 on 2020-02-08 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_topic_ower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='ower',
            new_name='owner',
        ),
    ]
